baseURL = "https://wuwu.github.io/ggronert/"
#baseURL = "https://galerie-gronert.netlify.com/"
languageCode = "en-us"
title = "Krauter Garden"
theme = "wwweihnachten"
sectionPagesMenu = "main"
Paginate = 7
pygmentsCodeFences = true
pygmentsUseClasses = true
archetypeDir = "krauter_content/archetypes"
contentDir = "krauter_content/content"
publishDir= "docs"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
