#baseURL = "https://wuwu.github.io/ggronert/"
baseURL = "https://krauteratlas.netlify.com/"
languageCode = "en-us"
title = "Krauter Garden"
theme = "wwweihnachten"
sectionPagesMenu = "main"
Paginate = 12
pygmentsCodeFences = true
pygmentsUseClasses = true
archetypeDir = "archetypes"
contentDir = "content_netlify_cms"
publishDir= "public"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  featured_image = "/images/Franz_Marc_-_Dog_Lying_in_the_Snow_-_Google_Art_Project.jpg"
  recent_posts_number = 2
  custom_css = ['css/styles.css']
  custom_js = ['js/app.js']

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]

[outputs]
  home = ["HTML", "RSS", "Algolia"]