backend:
  name: git-gateway

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "krauter" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Kraut" # Used in the UI, ie.: "New Post"
    folder: "krauter_content/content/kraut" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "krauter_content/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
