backend:
  name: git-gateway

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "krauter" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Kraut" # Used in the UI, ie.: "New Post"
    folder: "content_netlify_cms/kraut" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Wissenschaftlicher Name", name: "wissenschaftlicher_name", widget: "string"}
      - {label: "Volkstümlicher Name", name: "volkstuemlicher_name", widget: "string", required: false}
      - {label: "Englischer Name", name: "englischer_name", widget: "string", required: false}
      - {label: "Pflanzen Familie", name: "pflanzen_familie", widget: "string", required: false}
      - {label: "Verwendete Pflanzenteile", name: "verwendete_pflanzenteile", widget: "string", required: false}
      - {label: "Ernte", name: "ernte_zeit", widget: "string", required: false}
      - label: "Tags", name: "tags", widget: "list", allow_add: false,  default: ["Jan","Feb","Mar","Apr","Mai","Jun","Jul","Aug""Sep","Okt","Nov","Dez"]
      - {label: "Tags", name: "tags", widget: "list", default: ["Kraut"], required: false}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content_netlify_cms/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content_netlify_cms/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
